# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c647047e8b8d9f6c3c028bbb72cfdb66c9b4a79a64cc622be809d2176560d38fcac6efc5cf46c7465f846f73c2493a6ccceda3bb67bb067188c85fcee503ba90

test:
  secret_key_base: 1c577814f20ce6a2424475ab392ae904273335e43e67614c30d1701c42faa26d7503c3531aa9f914a9f7d345548dc99352e8257f158c36e4fea7118f9a213274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
